### PR TITLE
More fixes for the vm directory

### PR DESCRIPTION
**Pull request by kalkin**
This time with right rebase

### CODE REVIEW

**Comment by kalkin** [comment]
@woju Why does travis fails? Just because of pylint errors in the beginning?

**Comment by marmarek** [comment]
Yes, exactly.

**Comment by marmarek** [comment]
Interesting: "R:102, 4: Method could be a function (no-self-use)" - that line is untouched for a long time...

**Comment by marmarek** [comment]
@woju what is status of this PR?

**Comment by marmarek** [comment]
@woju and others waiting for more than week? ...

**Comment by kalkin** [comment]
@marmarek I fixed all the travis mentioned issues. This all is part of my current master branch and in day to day use/test.

**Pull request merged**
